# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tablesEditForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TablesEditForm(object):
    def setupUi(self, TablesEditForm):
        TablesEditForm.setObjectName("TablesEditForm")
        TablesEditForm.setWindowModality(QtCore.Qt.ApplicationModal)
        TablesEditForm.resize(413, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(TablesEditForm)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tableView = QtWidgets.QTableView(TablesEditForm)
        self.tableView.setObjectName("tableView")
        self.verticalLayout.addWidget(self.tableView)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.add_btn = QtWidgets.QPushButton(TablesEditForm)
        self.add_btn.setObjectName("add_btn")
        self.horizontalLayout.addWidget(self.add_btn)
        self.delete_btn = QtWidgets.QPushButton(TablesEditForm)
        self.delete_btn.setObjectName("delete_btn")
        self.horizontalLayout.addWidget(self.delete_btn)
        self.close_btn = QtWidgets.QPushButton(TablesEditForm)
        self.close_btn.setObjectName("close_btn")
        self.horizontalLayout.addWidget(self.close_btn)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(TablesEditForm)
        QtCore.QMetaObject.connectSlotsByName(TablesEditForm)

    def retranslateUi(self, TablesEditForm):
        _translate = QtCore.QCoreApplication.translate
        TablesEditForm.setWindowTitle(_translate("TablesEditForm", "Таблица ..."))
        self.add_btn.setText(_translate("TablesEditForm", "Добавить"))
        self.delete_btn.setText(_translate("TablesEditForm", "Удалить"))
        self.close_btn.setText(_translate("TablesEditForm", "Закрыть окно"))
