# Generated by Django 3.1.7 on 2021-03-18 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LocationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Тип местоположения')),
            ],
        ),
        migrations.CreateModel(
            name='Responsible',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='ФИО отвественного')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Статус')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Тип')),
            ],
        ),
        migrations.CreateModel(
            name='SubType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Подтип')),
                ('refers_to_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manage_items.type')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название местоположения')),
                ('location_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manage_items.locationtype')),
            ],
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование')),
                ('inv_number', models.CharField(blank=True, max_length=30, unique=True, verbose_name='Инвентарный номер')),
                ('comment', models.TextField(max_length=1500, verbose_name='Примечание')),
                ('is_on_balance', models.BooleanField(default=True, verbose_name='На балансе?')),
                ('bought_date', models.DateField(auto_now=True, verbose_name='Дата приобретения')),
                ('can_be_used', models.IntegerField(default=5, verbose_name='Время эксплуатации')),
                ('item_subtype', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manage_items.subtype', verbose_name='Подтип')),
                ('item_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manage_items.type', verbose_name='Тип')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manage_items.location', verbose_name='Местонахождение')),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manage_items.responsible', verbose_name='Ответственный')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manage_items.status', verbose_name='Статус')),
            ],
        ),
    ]
