# Generated by Django 3.1.7 on 2021-03-18 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_items', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Goods',
            new_name='Good',
        ),
    ]
